name: Go Tests

on:
  push:
    paths: &go-paths
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    types: [opened, synchronize]
    paths: *go-paths

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./...
