name: Go Tests

on:
  workflow_dispatch:
  push:
    paths: &go-paths
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    types: [opened, synchronize]
    paths: *go-paths

jobs:
  test:
    name: test (go v${{ matrix.go-version }})
    strategy:
      matrix:
        go-version: ['1.25']
    runs-on: ubuntu-latest
    steps:
      - name: Install Essentials
        run: |
          apt-get update && apt-get install -y nodejs npm
      - name: Checkout code
        uses: https://code.forgejo.org/actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./...
